fork = true
frame = "none"
idle = false
no-multigrid = true
srgb = true
tabs = true
title-hidden = false
vsync = true
maximized = true
opengl = true

[font]
normal = { family = "Maple Mono NF", style = "W500" }
italic = { family = "Maple Mono NF", style = "W500" }
bold = { family = "Maple Mono NF", style = "W500" }
bold_italic = { family = "Maple Mono NF", style = "W500" }
size = 9
hinting = "none"
edging = "antialias"

[box-drawing]
mode = "native"
