START_CHARGE_THRESH_BAT1=20
STOP_CHARGE_THRESH_BAT1=80
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_SCALING_GOVERNOR_ON_SAV=powersave
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
CPU_BOOST_ON_SAV=0
DISK_DEVICES="nvme0n1"
DISK_APM_LEVEL_ON_AC="254"
DISK_APM_LEVEL_ON_BAT="128"
PCIE_ASPM_ON_AC=default
PCIE_ASPM_ON_BAT=powersupersave
PCIE_ASPM_ON_SAV=powersupersave
CPU_DRIVER_OPMODE_ON_AC=active
CPU_DRIVER_OPMODE_ON_BAT=active
CPU_DRIVER_OPMODE_ON_SAV=active
CPU_ENERGY_PERF_POLICY_ON_AC=balance_performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power
CPU_ENERGY_PERF_POLICY_ON_SAV=power
CPU_MIN_PERF_ON_AC=0
CPU_MAX_PERF_ON_AC=100
CPU_MIN_PERF_ON_BAT=0
CPU_MAX_PERF_ON_BAT=100
CPU_MIN_PERF_ON_SAV=0
CPU_MAX_PERF_ON_SAV=50
CPU_HWP_DYN_BOOST_ON_AC=1
CPU_HWP_DYN_BOOST_ON_BAT=0
CPU_HWP_DYN_BOOST_ON_SAV=0
CPU_HWP_ON_BAT=power
#INTEL_GPU_MIN_FREQ_ON_AC=0
#INTEL_GPU_MIN_FREQ_ON_BAT=100
#INTEL_GPU_MIN_FREQ_ON_SAV=100
#INTEL_GPU_MAX_FREQ_ON_AC=0
#INTEL_GPU_MAX_FREQ_ON_BAT=450
#INTEL_GPU_MAX_FREQ_ON_SAV=300
#INTEL_GPU_BOOST_FREQ_ON_AC=0
#INTEL_GPU_BOOST_FREQ_ON_BAT=450
#INTEL_GPU_BOOST_FREQ_ON_SAV=300
MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=90
MAX_LOST_WORK_SECS_ON_SAV=120
AHCI_RUNTIME_PM_ON_AC=on
AHCI_RUNTIME_PM_ON_BAT=auto
AHCI_RUNTIME_PM_ON_SAV=auto
AHCI_RUNTIME_PM_TIMEOUT=15
SOUND_POWER_SAVE_ON_AC=1
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_ON_SAV=1
SOUND_POWER_SAVE_CONTROLLER=Y
USB_AUTOSUSPEND=1
DEVICES_TO_DISABLE_ON_STARTUP="bluetooth"
DEVICES_TO_DISABLE_ON_LAN_CONNECT="wifi"
DEVICES_TO_ENABLE_ON_LAN_DISCONNECT="wifi"
PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=cool
PLATFORM_PROFILE_ON_SAV=low-power
#TLP_AUTO_SWITCH=1
TLP_PROFILE_AC=PRF
TLP_PROFILE_BAT=BAT
TLP_PROFILE_SAV=SAV
SCHED_POWEREFFICIENT_ON_BAT=1
